backend:
  name: 'github'
  repo: 'digpublishing/digpublishing.github.io'
  branch: 'master'
  site_domain: 'mupudig.netlify.app' # Netlify Site that hosts OAuth
media_folder: 'assets/images/uploads'
slug:
  clean_accesns: true
collections:

  # Collection of webinars
  - label: 'Webinar'
    name: 'webinar'
    folder: 'webinars/_posts/'
    editor:
      preview: false
    create: true
    delete: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'webinar'}
      - {label: 'Title', name: 'title', widget: 'string', required: true}
      - {label: 'Youtube URL to Embed', name: 'video_url', widget: 'string'}
      - {label: 'Youtube Video ID', name: 'video_id', widget: 'string'}
      - {
        label: 'Date Scheduled',
        name: 'date',
        widget: 'datetime',
        date_format: 'MMMM D, YYYY',
        required: true
      }
      - {label: 'Tags', name: 'tags', widget: 'list'}
      - {label: 'Content', name: 'body', widget: 'markdown', required: true}

  # Collection of custom pages
  - label: 'Pages'
    name: 'custom_pages'
    folder: '/'
    filter: {field: 'layout', value: 'page'}
    editor:
      preview: false
    create: true
    delete: true
    slug: '{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'page'}
      - {label: 'Title', name: 'title', widget: 'string', required: true}
      - {label: 'Content', name: 'body', widget: 'markdown', required: true}

  # Required one-off pages
  - label: 'Home'
    editor:
      preview: false
    delete: false
    name: 'home'
    files:
      - label: 'Home'
        name: 'home'
        file: 'index.md'
        fields:
          - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'home'}
          - {label: 'Content', name: 'body', widget: 'markdown', required: true}

  # Data pages
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
    - file: '_data/committee.yml'
      label: 'Committee'
      name: 'committee'
      fields:
        - widget: 'list'
          name: 'members'
          label: 'Members'
          required: true
          fields:
            - {label: 'Name', name: 'name', widget: 'string', required: true}
            - {label: 'Affiliation', name: 'affiliation', widget: 'string', required: true}
            - {label: 'Email', name: 'email', widget: 'string'}
            - {label: 'Are they a moderator?', name: 'isModerator', widget: 'boolean', required: true, default: false}
            - {label: 'Bio', name: 'bio', widget: 'markdown'}
    - file: '_data/navigation.yml'
      label: 'Navigation'
      name: 'navigation'
      fields:
        - widget: 'list'
          name: 'items'
          label: 'Navigation Items'
          required: true
          fields:
            - {label: 'Name', name: 'name', widget: 'string', required: true}
            - {label: 'Link', name: 'link', widget: 'string', required: true}
